### ISSUE TITLE
Lösungszettel anlegen: Lösungszettel-UUID im Kind espeichert, aber kein Lösungszettel mit dieser UUID vorhanden

### ISSUE THREAD

**Issue by heike2718** [heike2718/minikaenguru#291]
Transaktionsmanagement prüfen.

Resilientes ExceptionHandling: wenn in LoesungszettelService.loesungszettelAnlegen der Lösungszettel nicht gefunden wird, muss das Kind aktualisiert werden mit einer Fehlermeldung, damit das Erfassen des Lösungszettels wiederholt werden kann.

**Comment by heike2718** [comment]
idRef=86831cb2a4b84244_22ea1dc4 - uuid=22ea1dc4...: No value present: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at de.egladil.web.mk_gateway.domain.loesungszettel.LoesungszettelService.loesungszettelAnlegen(LoesungszettelService.java:307)
	at de.egladil.web.mk_gateway.domain.loesungszettel.LoesungszettelService_Subclass.loesungszettelAnlegen$$superaccessor4(LoesungszettelService_Subclass.zig:705)
